'use strict';
const $=id=>document.getElementById(id);
const categories={'Table Topics':[60,90,120],'Evaluation':[120,150,180],'Ice Breaker':[240,300,360],'Most Other Speeches':[300,360,420],'General Evaluator':[120,180,240],'Meeting Introduction':[60,90,120],'Custom':[300,360,420]};
Object.keys(categories).filter(c=>!Array.from($('category').options).some(o=>o.value===c)).forEach(c=>{const o=document.createElement('option');o.value=o.textContent=c;$('category').append(o)});
function parseTime(v){return /^[0-9]+:[0-5][0-9]$/.test(v)?Number(v.split(':')[0])*60+Number(v.split(':')[1]):NaN}
function currentTimes(){return running&&pmTimerV5.active?pmTimerV5.active.times||categories[pmTimerV5.active.category]:$('category').value==='Custom'?['customG','customY','customR'].map(id=>parseTime($(id).value)):categories[$('category').value]}
function entryTimes(e){return e.times||categories[e.category]}
function entryResult(e){return result(e.seconds,e.category,entryTimes(e),e.earlyGrace)}
function selectedEntries(){return pmTimerV5.entries.filter(e=>e.date===$('reportDate').value)}
let tmMeetingInfo={},pmTimerV5={entries:[],active:null},storageOK=true;
try{tmMeetingInfo=JSON.parse(localStorage.getItem('tmMeetingInfo')||'{}')||{};pmTimerV5=JSON.parse(localStorage.getItem('pmTimerV5')||'null')||pmTimerV5;if(!Array.isArray(pmTimerV5.entries))pmTimerV5.entries=[]}catch{storageOK=false}
const today=new Date();$('date').value=tmMeetingInfo.date||`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;$('timerName').value=tmMeetingInfo.timerName||'';$('participant').value=tmMeetingInfo.participant||'';
function announce(t){$('announce').textContent=t}function save(){tmMeetingInfo={date:$('date').value,timerName:$('timerName').value,participant:$('participant').value,earlyGrace:$('earlyGrace').checked};try{localStorage.setItem('tmMeetingInfo',JSON.stringify(tmMeetingInfo));localStorage.setItem('pmTimerV5',JSON.stringify(pmTimerV5))}catch{storageOK=false;document.querySelector('.local').textContent='Storage unavailable';announce('Browser storage unavailable. Export your report to keep it.')}}
['date','timerName','participant'].forEach(id=>$(id).addEventListener('input',save));
function fmt(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function result(s,c,t=categories[c],early=false){const [g,y,r]=t;return s<g?(early&&s>=Math.max(0,g-30)?'Before minimum · allowed grace':'Early'):s<=r?'Within Time':s<=r+30?'30-Second Grace':'Exceeded Grace'}
let running=!!pmTimerV5.active,elapsed=0,lastState='',editing=null;
if(running){$('participant').value=pmTimerV5.active.name;$('category').value=pmTimerV5.active.category;$('date').value=pmTimerV5.active.date;$('timerName').value=pmTimerV5.active.timerName;if(pmTimerV5.active.times)['customG','customY','customR'].forEach((id,i)=>$(id).value=fmt(pmTimerV5.active.times[i]))} $('earlyGrace').checked=running?!!pmTimerV5.active.earlyGrace:!!tmMeetingInfo.earlyGrace;$('reportDate').value=$('date').value;
function thresholds(){const [g,y,r]=currentTimes();$('g').textContent=fmt(g);$('y').textContent=fmt(y);$('r').textContent=fmt(r);$('progress').setAttribute('aria-valuemax',r)}
function lock(){['participant','category','date','timerName','customG','customY','customR','earlyGrace','newMeeting'].forEach(id=>$(id).disabled=running);$('start').disabled=running;$('stop').disabled=!running;$('next').disabled=running}
function paint(){if(running)elapsed=Math.max(0,Math.floor((Date.now()-pmTimerV5.active.startedAt)/1000));const [g,y,r]=currentTimes();let color=elapsed>=r?'red':elapsed>=y?'yellow':elapsed>=g?'green':'';const state=elapsed>r+30?'exceeded':elapsed>r?'grace':color||'early';document.body.dataset.signal=color;$('clock').textContent=fmt(elapsed);$('shape').textContent=color==='green'?'●':color==='yellow'?'◆':color==='red'?'■':'—';$('signal').textContent=!running&&elapsed===0?'Ready when you are':color==='green'?'Minimum time reached':color==='yellow'?'Wrap up':color==='red'?'Official maximum reached':'Timing in progress';$('status').textContent=!running&&elapsed===0?'Press Start to begin timing':state==='exceeded'?'Exceeded Grace':state==='grace'?'30-Second Grace':elapsed>=g?'Within Time':'Before minimum time';$('over').textContent=state==='exceeded'?`Over the 30-second grace by ${fmt(elapsed-r-30)}`:state==='grace'?`Grace ends at ${fmt(r+30)}`:'';$('bar').style.width=Math.min(100,elapsed/r*100)+'%';$('progress').setAttribute('aria-valuenow',Math.min(elapsed,r));$('progress').setAttribute('aria-valuetext',`${fmt(elapsed)} elapsed; maximum ${fmt(r)}`);if(state!==lastState){if(running)announce(state==='exceeded'?'Exceeded the 30-second grace. Timer continues running.':state==='grace'?'30-second grace period.':$('signal').textContent);lastState=state}}
$('category').onchange=()=>{elapsed=0;$('customTiming').hidden=$('category').value!=='Custom';$('presetNote').textContent=['General Evaluator','Meeting Introduction'].includes($('category').value)?'Suggested club timing. Select Custom to match your agenda.':'';thresholds();paint()};$('start').onclick=()=>{if(!$('participant').value.trim()){$('participant').focus();announce('Enter a participant name to start.');return}const times=currentTimes();if(!times.every(Number.isSafeInteger)||!(0<times[0]&&times[0]<times[1]&&times[1]<times[2])){announce('Enter valid mm:ss times with Green before Yellow before Red.');$('customG').focus();return}elapsed=0;lastState='';pmTimerV5.active={name:$('participant').value.trim(),category:$('category').value,times:times.slice(),earlyGrace:$('earlyGrace').checked,startedAt:Date.now(),date:$('date').value,timerName:$('timerName').value};running=true;save();lock();paint();$('stop').focus()};
$('stop').onclick=()=>{paint();const a=pmTimerV5.active;pmTimerV5.entries.push({id:Date.now()+Math.random(),name:a.name,category:a.category,times:a.times,earlyGrace:a.earlyGrace,seconds:elapsed,date:a.date,timerName:a.timerName});running=false;pmTimerV5.active=null;save();lock();render();announce(`Logged ${a.name}, ${fmt(elapsed)}, ${result(elapsed,a.category,a.times,a.earlyGrace)}.`);$('start').focus()};
$('reset').onclick=()=>{if(running&&!confirm('Discard the current timing without logging?'))return;running=false;pmTimerV5.active=null;elapsed=0;lastState='';save();lock();paint();announce('Timer reset');$('start').focus()};
function cell(tr,t){const td=document.createElement('td');td.textContent=t;tr.append(td);return td}
function render(){$('rows').replaceChildren();const entries=selectedEntries();$('empty').hidden=entries.length>0;$('table').hidden=!entries.length;entries.forEach(e=>{const tr=document.createElement('tr');cell(tr,e.name);cell(tr,e.category);cell(tr,fmt(e.seconds));cell(tr,entryResult(e));const td=cell(tr,'');const edit=document.createElement('button');edit.textContent='Edit';edit.setAttribute('aria-label',`Edit ${e.name}`);edit.onclick=()=>{editing=e.id;$('editName').value=e.name;$('editCategory').value=e.category;$('editTime').value=fmt(e.seconds);$('editDate').value=e.date;$('editTimer').value=e.timerName;$('editDialog').showModal()};const del=document.createElement('button');del.textContent='Delete';del.setAttribute('aria-label',`Delete ${e.name}`);del.onclick=()=>{if(confirm(`Delete ${e.name}'s entry?`)){pmTimerV5.entries=pmTimerV5.entries.filter(x=>x.id!==e.id);save();render();announce('Entry deleted')}};td.append(edit,del);$('rows').append(tr)});$('csv').disabled=$('jpg').disabled=!entries.length;renderReport(entries)}
$('editCategory').innerHTML=$('category').innerHTML;$('editForm').onsubmit=e=>{e.preventDefault();const entry=pmTimerV5.entries.find(x=>x.id===editing);const parts=$('editTime').value.split(':').map(Number);if(!$('editName').value.trim()||!Number.isSafeInteger(parts[0]*60+parts[1]))return;if(entry.category!==$('editCategory').value)entry.times=categories[$('editCategory').value].slice();Object.assign(entry,{date:$('editDate').value,timerName:$('editTimer').value,name:$('editName').value.trim(),category:$('editCategory').value,seconds:parts[0]*60+parts[1]});save();render();$('editDialog').close();announce('Entry updated')};$('cancel').onclick=()=>$('editDialog').close();
function download(blob,ext,suffix=''){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=`toastmasters-report-${$('reportDate').value||'meeting'}${suffix}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);announce(`${ext.toUpperCase()} report downloaded`)}
function csvField(v){let t=String(v??'');if(/^[=+@\-\t\r]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"'}
$('csv').onclick=()=>{const rows=[['Meeting Date','Timer Name','Participant','Category','Elapsed','Result','Green','Yellow','Red','Grace Ends','Before-minimum allowance'],...selectedEntries().map(e=>[e.date,e.timerName,e.name,e.category,fmt(e.seconds),entryResult(e),...entryTimes(e).map(fmt),fmt(entryTimes(e)[2]+30),e.earlyGrace?'30 seconds':'None'])];download(new Blob(['\ufeff'+rows.map(row=>row.map(csvField).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'csv')};
$('jpg').onclick=()=>{const entries=selectedEntries();const perPage=24;for(let page=0;page<Math.ceil(entries.length/perPage);page++){const batch=entries.slice(page*perPage,(page+1)*perPage),c=document.createElement('canvas');c.width=1600;c.height=340+batch.length*90;const ctx=c.getContext('2d');ctx.fillStyle='#eef3f3';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#213c43';ctx.font='48px Georgia';ctx.fillText('Toastmasters Timer · Meeting Report',70,85);ctx.font='24px sans-serif';ctx.fillText(`Meeting: ${$('reportDate').value}    Allotted ranges are shown beneath each category`,70,140);ctx.font='20px sans-serif';ctx.fillText('Meeting date / Timer',70,225);ctx.fillText('Participant',400,225);ctx.fillText('Category',810,225);ctx.fillText('Time',1200,225);ctx.fillText('Result',1320,225);batch.forEach((e,i)=>{const y=270+i*90;ctx.fillStyle=i%2?'#f6f9f9':'#ffffff';ctx.fillRect(50,y-26,1500,85);ctx.fillStyle='#213c43';ctx.font='20px sans-serif';const clip=(s,w)=>{while(ctx.measureText(s).width>w)s=s.slice(0,-2)+'…';return s};ctx.fillText(e.date,70,y);ctx.fillText(clip(e.timerName||'—',300),70,y+28);ctx.fillText(clip(e.name,380),400,y);ctx.fillText(e.category,810,y);ctx.fillText(`${fmt(entryTimes(e)[0])}–${fmt(entryTimes(e)[2])}`,810,y+28);ctx.fillText(fmt(e.seconds),1200,y);ctx.font='18px sans-serif';ctx.fillText(entryResult(e),1320,y)});ctx.font='18px sans-serif';ctx.fillText(`30-second grace included · Page ${page+1} of ${Math.ceil(entries.length/perPage)}`,70,c.height-30);c.toBlob(b=>{if(b)download(b,'jpg',`-page-${page+1}`);else announce('Image export failed. Please use CSV.')},'image/jpeg',.94)}};
function renderReport(entries){$('reportText').replaceChildren();const intro=document.createElement('p');intro.textContent=`Timer’s report for ${$('reportDate').value}.`; $('reportText').append(intro);entries.forEach(e=>{const p=document.createElement('p'),t=entryTimes(e);p.textContent=`${e.name} — ${e.category}. Allotted time: ${fmt(t[0])} to ${fmt(t[2])}. Actual time: ${fmt(e.seconds)}. ${entryResult(e)}.`;$('reportText').append(p)})}
$('reportDate').onchange=render;
$('date').addEventListener('change',()=>{$('reportDate').value=$('date').value;render()});
$('earlyGrace').onchange=save;
['customG','customY','customR'].forEach(id=>$(id).oninput=()=>{const t=currentTimes();if(t.every(Number.isFinite)&&t[0]>0&&t[0]<t[1]&&t[1]<t[2]){thresholds();paint()}});
$('next').onclick=()=>{elapsed=0;lastState='';$('participant').value='';document.body.classList.remove('speaker-view');$('speaker').setAttribute('aria-pressed','false');save();paint();$('participant').focus();announce('Ready for the next speaker')};
$('newMeeting').onclick=()=>{elapsed=0;$('participant').value='';$('date').value=new Date().toLocaleDateString('en-CA');$('reportDate').value=$('date').value;save();paint();render();$('date').focus();announce('Meeting setup ready. Select the meeting date. Existing records are retained.')};
$('speaker').onclick=()=>{const enabled=!document.body.classList.contains('speaker-view');document.body.classList.toggle('speaker-view',enabled);$('speaker').setAttribute('aria-pressed',String(enabled));setFocusView(true)};
let focusScroll=0;
function setFocusView(enabled){
 const timer=$('timer'),button=$('fullscreen');
 if(enabled&&!document.body.classList.contains('focus-view'))focusScroll=window.scrollY;if(!enabled){document.body.classList.remove('speaker-view');$('speaker').setAttribute('aria-pressed','false')}
 document.body.classList.toggle('focus-view',enabled);
 document.querySelectorAll('header,.intro,.meeting,.guide,.logs,footer,.skip').forEach(el=>{el.inert=enabled;});
 button.textContent=enabled?'Exit focus view ✕':'Focus view ↗';
 button.setAttribute('aria-pressed',String(enabled));
 if(enabled){timer.scrollTop=0;button.focus();}else{window.scrollTo(0,focusScroll);button.focus();}
 announce(enabled?'Focus view opened. Press Escape or Exit focus view to return.':'Focus view closed.');
}
$('fullscreen').setAttribute('aria-pressed','false');
$('fullscreen').onclick=()=>setFocusView(!document.body.classList.contains('focus-view'));
document.addEventListener('keydown',event=>{
 if(!document.body.classList.contains('focus-view'))return;
 if(event.key==='Escape'){event.preventDefault();setFocusView(false);return;}
 if(event.key==='Tab'){
  const items=Array.from($('timer').querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)')).filter(el=>el.getClientRects().length);
  const first=items[0],last=items[items.length-1];
  if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
  else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
 }
});
$('customTiming').hidden=$('category').value!=='Custom';setInterval(paint,200);thresholds();lock();paint();render();save();
